version: "3.3"
services:
  flight_review_app:
    # image: px4flightreview
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    volumes:
      - ./data:/opt/service/data
      - ${PWD}/config_default.ini:/opt/service/config_default.ini:ro
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
      args:
        - TZ=${TZ}
    ports:
      - 80:80
      - 443:443
    links:
      - flight_review_app
    depends_on:
      - flight_review_app

