version: "3.3"
services:
  flight_review_app:
    # image: px4flightreview
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    volumes:
      - ./data:/opt/service/data
      - ./app/config_default.ini:/opt/service/config_default.ini:ro
      - ./app/config_user.ini:/opt/service/config_user.ini:ro
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.ssl
      args:
        - TZ=${TZ}
    env_file: .env
    
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - ./logs/nginx:/var/log/nginx/
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    links:
      - flight_review_app
    depends_on:
      - flight_review_app


