version: "3.3"
services:
  flight_review_app:
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: always
    network_mode: bridge
    ports:
     - 5006:5006
    env_file: .env
    command: /opt/service/run.sh
    volumes:
      - ./app:/opt/service/
      - ./data:/opt/service/data
      # Absolute for volume a file.
      - ${PWD}/config_default.ini:/opt/service/config_default.ini:ro