name: Deployment

on:
  push:
    branches: [sel_branch]
  pull_request:
    branches:
    - 'sel_branch'

jobs:
  deploy:
    if: github.ref == 'refs/heads/sel_branch'
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$PRIVATE_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $HOST_NAME
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.USER_NAME }}
          PRIVATE_KEY: ${{ secrets.STAGING_PRIVATE_KEY }}
          HOST_NAME: ${{ secrets.STAGING_HOST_NAME }}

      - uses: actions/checkout@v2
      - name: Deploy
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          USER_NAME: ${{ secrets.USER_NAME }}
          HOST_NAME: ${{ secrets.HOST_NAME }}
        run: |
          ssh ${USER_NAME}@${HOST_NAME}
          # ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOST_NAME}
          ls
        
      #     # SSH接続して、git pullする
      #     echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
      #     cd /home/${USER_NAME}/flight_review &&
      #     git checkout sel_branch &&
      #     git fetch --all &&
      #     echo "Done fetch"
      #     # git reset --hard origin/sel_branch &&
      #     # git pull origin master
      #     # 