name: Deployment

on:
  push:
    branches:
    - 'sel_branch'
  pull_request:
    branches:
    - 'sel_branch'
    types: [closed]

# sel_branchに対するPRが閉じたら、Deployを実行する
jobs:
  deploy:
    if: github.ref == 'refs/heads/sel_branch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        env:
          USER_NAME: ${{ secrets.USER_NAME }}
          HOST_NAME: ${{ secrets.HOST_NAME }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DOMAIN: ${{ secrets.DOMAIN }}
          PORT: ${{ secrets.PORT }}
          CERT_PATH: ${{ secrets.CERT_PATH }}
          USE_PROXY: ${{ secrets.USE_PROXY }}
          NGINX_CONF: ${{ secrets.NGINX_CONF }}
        run: |
          echo "$SECRET_KEY" > secret_key
          chmod 600 secret_key
          # SSH接続して、git pullする
          ssh -oStrictHostKeyChecking=no ${USER_NAME}@${HOST_NAME} -i secret_key "cd ~/flight_review && git checkout sel_branch && git pull origin sel_branch"
          ssh -oStrictHostKeyChecking=no ${USER_NAME}@${HOST_NAME} -i secret_key "cd ~/flight_review && docker-compose -f docker-compose.prod.yml down"
          ssh -oStrictHostKeyChecking=no ${USER_NAME}@${HOST_NAME} -i secret_key "cd ~/flight_review && docker-compose -f docker-compose.prod.yml build --no-cache"
          ssh -oStrictHostKeyChecking=no ${USER_NAME}@${HOST_NAME} -i secret_key "cd ~/flight_review && chmod ./init-letsencrypt.sh"
          ssh -oStrictHostKeyChecking=no ${USER_NAME}@${HOST_NAME} -i secret_key "cd ~/flight_review && ./init-letsencrypt.sh"
