name: Deployment

on:
  push:
    branches: [sel_branch]
  pull_request:
    branches:
    - 'sel_branch'

jobs:
  deploy:
    if: github.ref == 'refs/heads/sel_branch'
    runs-on: ubuntu-latest
    steps:
      # - name: Public IP
      #   id: ip
      #   uses: haythem/public-ip@v1

      - uses: actions/checkout@v2
      - name: Deploy
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          USER_NAME: ${{ secrets.USER_NAME }}
          HOST_NAME: ${{ secrets.HOST_NAME }}
        run: |
          # https://github.com/haythem/public-ip
          IP_ADDRESS=`echo ${{ steps.ip.outputs.ipv4 }}`

          # AWS CLIをインストール
          #curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          #unzip awscliv2.zip
          #sudo ./aws/install
          #aws --version

          # AWS CLIに設定をする
          #printf "${ACCESS_KEY}\n${SECRET_ACCESS_KEY}\nap-northeast-1\njson\n" | aws configure --profile eyemovic-dev
          #aws configure get aws_access_key_id --profile eyemovic-dev

          # SSHポートを開放する
          #aws --profile eyemovic-dev ec2 authorize-security-group-ingress --group-id ${SECURITY_GROUP} --protocol tcp --port 22 --cidr "$IP_ADDRESS"/32

          # SSH接続して、git pullする
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOST_NAME} '
          cd /home/${USER_NAME}/flight_review &&
          git checkout sel_branch &&
          git fetch --all &&
          echo "Done fetch"
          # git reset --hard origin/sel_branch &&
          # git pull origin master
          # 