name: Deployment

on:
  push:
    branches: [sel_branch]
  pull_request:
    branches:
    - 'sel_branch'

jobs:
  deploy:
    if: github.ref == 'refs/heads/sel_branch'
    runs-on: ubuntu-latest
    steps:
      - name:
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PRIVATE_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Deploy
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          USER_NAME: ${{ secrets.USER_NAME }}
          HOST_NAME: ${{ secrets.HOST_NAME }}
        run: |
          ssh -o StrictHostKeyChecking=no ${USER_NAME}@${HOST_NAME}
          ls
        
      #     # SSH接続して、git pullする
      #     echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
      #     cd /home/${USER_NAME}/flight_review &&
      #     git checkout sel_branch &&
      #     git fetch --all &&
      #     echo "Done fetch"
      #     # git reset --hard origin/sel_branch &&
      #     # git pull origin master
      #     # 